services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - /data/mosquitto/config:/mosquitto/config
      - /data/mosquitto/data:/mosquitto/data
      - /tmp/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    restart: unless-stopped
