---
services:
  foundry:
    image: foundry
    container_name: foundry-crpalmer
    volumes:
      - type: bind
        source: /home/crpalmer/foundry/data
        target: /data
    ports:
      - "1234:30000"
    restart: unless-stopped
