services:
  foundry:
    image: foundry
    container_name: foundry-crpalmer
    environment:
        VERSION: 13
    volumes:
      - type: bind
        source: /data/foundry
        target: /data
    ports:
      - "30000:30000"
    restart: unless-stopped

  foundry-james:
    image: foundry
    container_name: foundry-james
    environment:
        VERSION: 13
    volumes:
      - type: bind
        source: /data/james-foundry
        target: /data
    ports:
      - "31000:30000"
    restart: unless-stopped

  foundry-test:
    image: foundry
    container_name: foundry-test
    environment:
        VERSION: 14
    volumes:
      - type: bind
        source: /data/test-foundry
        target: /data
    ports:
      - "32000:30000"
    restart: unless-stopped
